version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Compile chapters
          command: |
            mkdir .chapters
            find . -type f -name "*.md" -exec cp {} .chapters/
      - run:
          name: Merge chapters
          command: cat `ls -Q .chapters | sort` > .merged.md
