version: 2
jobs:
  build:
    docker:
      - image: jagregory/pandoc
    steps:
      - checkout
      - run:
          name: Download extra dependencies
          command: apt-get update -y && apt-get install -y wget
      - run:
          name: Retrieve template
          command: |
            mkdir -p ~/.pandoc/templates
            wget -O ~/.pandoc/templates/wage.latex https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex
      - run:
          name: Merge chapters
          command: find chapters -type f -name "*.md" -exec cat {} \; > wage.md
      - run:
          name: Build PDF (Eisvogel template)
          command: pandoc wage.md -o wage.eisvogel.pdf --from markdown --template wage --listings
      - run:
          name: Build PDF (Original LaTeX)
          command: pandoc wage.md -o wage.pdf --from markdown --listings
      - store_artifacts:
          path: wage*.pdf