version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Compile chapters
          command: |
            mkdir -p /tmp/chapters
            find . -type f -name "*.md" -exec cp {} /tmp/chapters/ \;
      - run:
          name: Merge chapters
          command: cat `ls -Q /tmp/chapters | sort` > .merged.md
