version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Compile chapters
          command: |
            ls -QR | grep .md | sort | while read chapter
            do
              cat $chapter >> .merged
            done
