version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Compile chapter list
          command: ls -R | grep .md | sort > .files
      - run:
          name: Merge chapter
          command: |
            cat .files | while read chapter
            do
              cat $chapter >> .merged
            done
