version: 2
jobs:
  build:
    docker:
      - image: jagregory/pandoc
    steps:
      - checkout
      - run:
          name: Download extra dependencies
          command: apt-get update -y && apt-get install -y wget
      - run:
          name: Retrieve template
          command: |
            mkdir -p ~/.pandoc/templates
            mkdir documents
            wget -O ~/.pandoc/templates/wage.latex https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex
      - run:
          name: Merge chapters
          command: find chapters -type f -name "*.md" | sort | xargs -I {} cat {} >> wage.md
      - run:
          name: Build PDF (Eisvogel template)
          command: pandoc wage.md metadata.yml -o documents/wage.eisvogel.pdf --from markdown --template wage --listings --toc
      - run:
          name: Build PDF (Original LaTeX)
          command: pandoc wage.md metadata.yml -o documents/wage.pdf --from markdown --listings --toc
      - store_artifacts:
          path: documents