version: 2
jobs:
  build:
    docker:
      - image: jagregory/pandoc
    steps:
      - checkout
      - run:
          name: Compile chapters
          command: |
            mkdir -p /tmp/chapters
            find . -type f -name "*.md" -exec cp {} /tmp/chapters/ \;
            rm /tmp/chapters/README.md
      - run:
          name: Merge chapters
          command: find /tmp/chapters -type f -exec cat {} > .merged.md \;
      - run:
          name: Build PDF
          command: pandoc .merged.md -s -o manuscrits.pdf
      - store_artifacts:
          path: manuscrits.pdf
